# TCGPlayer Card Monitoring Configuration

# URLs to monitor - add your specific card pages here
tcgplayer_pages_to_monitor:
  - "https://www.tcgplayer.com/product/649586/pokemon-japan-m-p-promotional-cards-pikachu-020-m-p"
  - "https://www.tcgplayer.com/product/593355/pokemon-sv-prismatic-evolutions-prismatic-evolutions-elite-trainer-box?page=1&Language=English"
  - "https://www.tcgplayer.com/product/593466/pokemon-sv-prismatic-evolutions-prismatic-evolutions-surprise-box?page=1&Language=English"
  - "https://www.tcgplayer.com/product/600518/pokemon-sv-prismatic-evolutions-prismatic-evolutions-booster-bundle?page=1&Language=English"
  - "https://www.tcgplayer.com/product/528038/pokemon-sv-paldean-fates-paldean-fates-booster-pack?page=1&Language=English"
  - "https://www.tcgplayer.com/product/504467/pokemon-sv-scarlet-and-violet-151-151-booster-pack?page=1&Language=English"

# Monitoring settings
monitoring:
  interval_seconds: 60  # Check every 60 seconds
  headless_mode: true   # Set to false to see browser window
  max_price_alert: 100.0  # Alert if any listing is under this price
  min_condition: "Lightly Played"  # Only monitor cards in this condition or better

# Alert settings
alerts:
  discord_webhook_url: "https://discord.com/api/webhooks/1420205527295721615/cevkt66p_FCRmPTkg1b4r0lUuejguOfZb4j1v_fo6u6Imb2AU3qVF2S6SdnAWbm6_oUP"
  alert_all_new_sales: true  # Alert for ALL new sales regardless of price
  email_alerts: false  # Set to true to enable email alerts
  alert_email: null  # Your email for alerts

# Data storage
storage:
  data_file: "card_data.json"
  log_file: "monitor.log"
